### ISSUE TITLE
Issue with running iHRIS locally

### ISSUE THREAD

**Issue by MrPink** [iHRIS/dockerfiles#2]
Hi,

I'm trying to run iHRIS locally with the `docker-compose -f docker-compose.manage.yml up` , I'm getting in the browser

`Fatal error: Uncaught Error: Class 'I2CE_Wrangler' not found in /var/lib/iHRIS/lib/4.3/ihris-manage/sites/blank/pages/index.php:59 Stack trace: #0 {main} thrown in /var/lib/iHRIS/lib/4.3/ihris-manage/sites/blank/pages/index.php on line 59`

I'm not a PHP person so I haven't got the faintest idea how to start debugging it.

Any pointers appreciated!
Will

**Comment by citizenrich** [comment]
Sorry about that. So, we have a couple of live bugs in upstream iHRIS recently that are affecting this. The dev builds of the container should work, but you'll need to shell into the container for the initial db migrations.

For the blank site:
```
docker-compose -f docker-compose.dev.manage.yml up -d
#then get into the container
docker exec -it ihris bash
```
Once there, you'll have a bash shell. 
```
cd manage
php index.php --update=1
```
That will run the initial migration. If it fails, then run it again.  Please let me know how you get on with that. I'll update the issue when fixes upstream are pushed.

**Comment by MrPink** [comment]
Many thanks! that's fixed it

**Comment by citizenrich** [comment]
closing this
